### PR TITLE
Let the plugins symlink spec/manageiq if they need

### PR DESCRIPTION
**Pull request by agrare**
Pass a MANAGEIQ_REPO env var when running bin/setup in the plugins if
they need to link to the core repo.

Plugin repo changes:

- [x] https://github.com/ManageIQ/manageiq/pull/19481

- [x] https://github.com/ManageIQ/manageiq-providers-ovirt/pull/426

- [x] https://github.com/ManageIQ/manageiq-ui-classic/pull/6390

- [x] https://github.com/ManageIQ/manageiq-providers-azure/pull/363

- [x] https://github.com/ManageIQ/manageiq-providers-kubevirt/pull/155

- [x] https://github.com/ManageIQ/manageiq-providers-openstack/pull/528

- [x] https://github.com/ManageIQ/manageiq-decorators/pull/24

- [x] https://github.com/ManageIQ/manageiq-providers-vmware/pull/474

- [x] https://github.com/ManageIQ/manageiq-providers-azure_stack/pull/20

- [x] https://github.com/ManageIQ/manageiq-providers-google/pull/115

- [x] https://github.com/ManageIQ/manageiq-content/pull/608

- [x] https://github.com/ManageIQ/manageiq-consumption/pull/171

- [x] https://github.com/ManageIQ/manageiq-providers-ansible_tower/pull/205

- [x] https://github.com/ManageIQ/manageiq-providers-scvmm/pull/142

- [x] https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/347

- [x] https://github.com/ManageIQ/manageiq-automation_engine/pull/389

- [x] https://github.com/ManageIQ/manageiq-providers-nuage/pull/193

- [x] https://github.com/ManageIQ/manageiq-api/pull/703

- [x] https://github.com/ManageIQ/manageiq-providers-dummy_provider/pull/20

- [x] https://github.com/ManageIQ/manageiq-providers-lenovo/pull/286

- [x] https://github.com/ManageIQ/manageiq-graphql/pull/84

- [x] https://github.com/ManageIQ/manageiq-providers-openshift/pull/153

- [x] https://github.com/ManageIQ/manageiq-providers-redfish/pull/98

- [x] https://github.com/ManageIQ/manageiq-providers-foreman/pull/51

- [ ] https://github.com/ManageIQ/manageiq-providers-amazon/pull/570

### CODE REVIEW

**Comment by agrare** [comment]
@Fryguy if you're good with https://github.com/ManageIQ/manageiq-providers-amazon/pull/570 I'll blast out that change to the rest of the plugins that need a spec/manageiq

**Comment by Fryguy** [comment]
I like the change in the plugin, and once we've settled on it, I think it should blast out.  We probably also want to change the generator to include these changes.

**Comment by agrare** [comment]
Okay blasted out all of the PRs and updated this to remove the "cleanup" step since that is done in the plugins now

**Comment by Fryguy** [comment]
@simaishi This may interest you.  If you pass MANAGEIQ_REPO as an env var during a plugin's bin/setup it will automatically symlink.

**Pull request merged**
